export interface Course {
  code: string;
  name: string;
  day: 'MON' | 'TUE' | 'WED' | 'THU' | 'FRI' | 'SAT';
  time: string;
  hall: string;
  lecturer: string;
  dept: 'CEN' | 'EEN' | 'CIV' | 'MEF' | 'CPE';
  level: 200 | 300 | 400 | 500;
}

export const COURSES: Course[] = [
  { code: "CEF238", name: "C/C++ Programming", day: "MON", time: "09:00-11:00", hall: "FET-BGFL", lecturer: "Dr. Nguti", dept: "CEN", level: 200 },
  { code: "CEF238", name: "C/C++ Programming", day: "MON", time: "11:00-13:00", hall: "FET-BGFL", lecturer: "Dr. Nguti", dept: "CEN", level: 200 },
  { code: "EEF368", name: "Microcontrollers & Microprocessors", day: "MON", time: "09:00-11:00", hall: "EE Laboratory", lecturer: "Prof. Tsafack / Dr. Tabetah", dept: "EEN", level: 300 },
  { code: "EEF368", name: "Microcontrollers & Microprocessors", day: "MON", time: "11:00-13:00", hall: "EE Laboratory", lecturer: "Prof. Tsafack / Dr. Tabetah", dept: "EEN", level: 300 },
  { code: "CIV408", name: "Geotechnics Lab I", day: "MON", time: "09:00-11:00", hall: "PG-LR5", lecturer: "Lontsi A / Njike / Kila", dept: "CIV", level: 400 },
  { code: "EEF460", name: "Feedback Systems Laboratory", day: "MON", time: "13:00-15:00", hall: "EE Laboratory", lecturer: "Dr. Wirnkar / Dr. Musong", dept: "EEN", level: 400 },
  { code: "CEF444", name: "AI & Machine Learning", day: "TUE", time: "07:00-09:00", hall: "FET-BFF-HALL2", lecturer: "Prof. Fute / Dr. Sop", dept: "CEN", level: 400 },
  { code: "CEF342", name: "Database and Design", day: "TUE", time: "07:00-09:00", hall: "FET-TECH3", lecturer: "Eng. Kingue Patrick", dept: "CEN", level: 300 },
  { code: "CEF364", name: "Local Area Computer Network", day: "TUE", time: "07:00-09:00", hall: "FET-TECH4", lecturer: "Mr. Glen Forcha", dept: "CEN", level: 300 },
  { code: "EEF262", name: "Physics for Engineering II", day: "TUE", time: "07:00-09:00", hall: "FET-BGFL", lecturer: "Dr. Job / Dr. Tabetah", dept: "EEN", level: 200 },
  { code: "EEF364", name: "Basic Telecommunications", day: "TUE", time: "07:00-09:00", hall: "FET-TECH4", lecturer: "Dr. Nkemeni / Mr. Forcha Glen", dept: "EEN", level: 300 },
  { code: "MEF204", name: "Basics of Mechanical Drawing", day: "TUE", time: "07:00-09:00", hall: "FET-BFF-HALL1", lecturer: "Dr. Temgoua / Dr. Aquigeh", dept: "MEF", level: 200 },
  { code: "CIV214", name: "Chemistry II", day: "TUE", time: "07:00-09:00", hall: "FET-TECH1", lecturer: "Tchetgnia Ngassam Ines", dept: "CIV", level: 200 },
  { code: "CIV310", name: "Thermodynamics", day: "TUE", time: "07:00-09:00", hall: "PG-LR5", lecturer: "Dr. Lontsi Agostiny", dept: "CIV", level: 300 },
  { code: "CPE208", name: "Chemical Process Principle", day: "TUE", time: "07:00-09:00", hall: "FET-TECH2", lecturer: "Dr Teiseh", dept: "CPE", level: 200 },
  { code: "CEF472", name: "Human Computer Interface", day: "TUE", time: "09:00-11:00", hall: "FET-TECH1", lecturer: "Dr Djouela Inès", dept: "CEN", level: 400 },
  { code: "CEF254", name: "Algebra", day: "TUE", time: "11:00-13:00", hall: "FET-BGFL", lecturer: "Dr Dor C.", dept: "CEN", level: 200 },
  { code: "CEF462", name: "Digital Image Processing", day: "TUE", time: "11:00-13:00", hall: "FET-TECH1", lecturer: "Dr Sop Deffo", dept: "CEN", level: 400 },
  { code: "CEF356", name: "Mobile Communications & Protocols", day: "TUE", time: "11:00-13:00", hall: "FET-BFF-HALL1", lecturer: "Dr. Nkemeni", dept: "CEN", level: 300 },
  { code: "EEF464", name: "Wireless & Mobile Communications", day: "TUE", time: "11:00-13:00", hall: "FET-BFF-HALL2", lecturer: "Dr. Sitamtze Youmbi", dept: "EEN", level: 400 },
  { code: "CIV202", name: "Materials Science & Technology", day: "TUE", time: "11:00-13:00", hall: "FET-TECH2", lecturer: "Tchetgnia Ngassam Ines", dept: "CIV", level: 200 },
  { code: "CPE304", name: "Reservoir Engineering", day: "TUE", time: "11:00-13:00", hall: "FET-TECH3", lecturer: "Dr. Victor Wotanie / Mr. Ayuk Samuel", dept: "CPE", level: 300 },
  { code: "CEF344", name: "Client-Server & Web App Development", day: "TUE", time: "13:00-15:00", hall: "PG-LR5", lecturer: "Dr Sop Deffo", dept: "CEN", level: 300 },
  { code: "CEF250", name: "Computer Architecture", day: "TUE", time: "13:00-15:00", hall: "FET-BGFL", lecturer: "Mr. Forcha Glen", dept: "CEN", level: 200 },
  { code: "EEF482", name: "Electric Machines II", day: "TUE", time: "13:00-15:00", hall: "FET-BFF-HALL2", lecturer: "Fotso Mbobda Christophe", dept: "EEN", level: 400 },
  { code: "CIV404", name: "Fluid Mechanics & Hydraulic Constructions", day: "TUE", time: "13:00-15:00", hall: "FET-TECH4", lecturer: "Lontsi Agostiny Marrios", dept: "CIV", level: 400 },
  { code: "MEF240", name: "Introduction to Thermodynamics", day: "TUE", time: "13:00-15:00", hall: "FET-TECH1", lecturer: "Prof. Fopah-Lele / Dr. Temgoua", dept: "MEF", level: 200 },
  { code: "MEF414", name: "CNC Machining", day: "TUE", time: "13:00-15:00", hall: "FET-TECH2", lecturer: "Azeufack", dept: "MEF", level: 400 },
  { code: "CEF440", name: "Internet & Mobile Programming", day: "TUE", time: "15:00-17:00", hall: "FET-BGFL", lecturer: "Dr Nkemeni V.", dept: "CEN", level: 400 },
  { code: "EEF466", name: "Antenna and Propagation", day: "TUE", time: "15:00-17:00", hall: "FET-TECH4", lecturer: "Engr. Baar David", dept: "EEN", level: 400 },
  { code: "EEF366", name: "Sequence Control", day: "TUE", time: "15:00-17:00", hall: "FET-TECH1", lecturer: "Dr. Nouadjep / Dr. Musong", dept: "EEN", level: 300 },
  { code: "MEF480", name: "Basics of Automobile Mechanics", day: "TUE", time: "15:00-17:00", hall: "FET-BFF-HALL1", lecturer: "Aquigeh", dept: "MEF", level: 400 },
  { code: "MEF354", name: "Thermodynamics", day: "TUE", time: "15:00-17:00", hall: "FET-TECH2", lecturer: "Temgoua Djouatsa Diane", dept: "MEF", level: 300 },
  { code: "CIV422", name: "Structural Analysis II", day: "TUE", time: "15:00-17:00", hall: "PG-LR5", lecturer: "Njike M. & Kila S.", dept: "CIV", level: 400 },
  { code: "CEF438", name: "Advanced Databases & Administration", day: "WED", time: "07:00-09:00", hall: "FET-BFF-HALL2", lecturer: "Dr Kamdjou", dept: "CEN", level: 400 },
  { code: "CEF432", name: "Network Security Fundamentals", day: "WED", time: "07:00-09:00", hall: "FET-TECH3", lecturer: "Dr Tsague A.", dept: "CEN", level: 400 },
  { code: "EEF262", name: "Physics for Engineering II", day: "WED", time: "07:00-09:00", hall: "FET-BGFL", lecturer: "Dr. Djob / Dr. Tabetah", dept: "EEN", level: 200 },
  { code: "CIV346", name: "Soil Mechanics", day: "WED", time: "07:00-09:00", hall: "FET-TECH1", lecturer: "Dr. Lontsi A. / Dr. Feumoe A.", dept: "CIV", level: 300 },
  { code: "CIV426", name: "Structural Design", day: "WED", time: "07:00-09:00", hall: "FET-BFF-HALL1", lecturer: "Njike Manette", dept: "CIV", level: 400 },
  { code: "MEF490", name: "Engineering Economy", day: "WED", time: "07:00-09:00", hall: "FET-TECH2", lecturer: "Dr. Seppo", dept: "MEF", level: 400 },
  { code: "CEF468", name: "Database & PHP Programming", day: "WED", time: "09:00-11:00", hall: "FET-BFF-HALL1", lecturer: "Eng. Djotchuang / Forcha Glen", dept: "CEN", level: 400 },
  { code: "CEF476", name: "Software Engineering & Design", day: "WED", time: "09:00-11:00", hall: "FET-TECH3", lecturer: "Dr Kamdjou / Dr Tsague", dept: "CEN", level: 400 },
  { code: "EEF262", name: "Physics for Engineering II", day: "WED", time: "09:00-11:00", hall: "FET-BGFL", lecturer: "Dr. Djob / Dr. Tabetah", dept: "EEN", level: 200 },
  { code: "CEF478", name: "Network Administration", day: "WED", time: "11:00-13:00", hall: "FET-TECH1", lecturer: "Mr. Forcha Glen", dept: "CEN", level: 400 },
  { code: "EEF262", name: "Physics for Engineering II", day: "WED", time: "11:00-13:00", hall: "FET-BGFL", lecturer: "Dr. Djob / Dr. Tabetah", dept: "EEN", level: 200 },
  { code: "CIV348", name: "Road and Various Networks", day: "WED", time: "11:00-13:00", hall: "PG-LR5", lecturer: "Dr. Meh A.", dept: "CIV", level: 300 },
  { code: "CIV502", name: "Reinforced Concrete 2", day: "WED", time: "11:00-13:00", hall: "FET-TECH4", lecturer: "Njike Manette / Kang Cedric", dept: "CIV", level: 500 },
  { code: "EEF262", name: "Physics for Engineering II", day: "WED", time: "15:00-17:00", hall: "FET-BGFL", lecturer: "Dr. Djob / Dr. Tabetah", dept: "EEN", level: 200 },
  { code: "EEF484", name: "Electrical Power Systems II", day: "THU", time: "07:00-09:00", hall: "FET-TECH1", lecturer: "Fotso Mbobda / Ayuketah", dept: "EEN", level: 400 },
  { code: "CIV410", name: "Fundamentals of BIM", day: "THU", time: "07:00-09:00", hall: "FET-BFF-HALL1", lecturer: "Mr. Kang Cederic / Chia", dept: "CIV", level: 400 },
  { code: "MEF416", name: "Basics of Industrial Automation", day: "THU", time: "07:00-09:00", hall: "FET-TECH2", lecturer: "TBA", dept: "MEF", level: 400 },
  { code: "MEF450", name: "Hydraulics and Pneumatics", day: "THU", time: "07:00-09:00", hall: "PG-LR5", lecturer: "Ejuh Che", dept: "MEF", level: 400 },
  { code: "EEF260", name: "Analog Electronics I", day: "THU", time: "07:00-09:00", hall: "FET-TECH4", lecturer: "Dr. Tabeta Marshall", dept: "EEN", level: 200 },
  { code: "CEF346", name: "Object Oriented Programming", day: "THU", time: "09:00-11:00", hall: "PG-LR5", lecturer: "Dr Djouela", dept: "CEN", level: 300 },
  { code: "CEF350", name: "Security and Cryptosystem", day: "THU", time: "09:00-11:00", hall: "FET-TECH1", lecturer: "Dr Tsague A.", dept: "CEN", level: 300 },
  { code: "EEF474", name: "Coding Theory", day: "THU", time: "09:00-11:00", hall: "FET-TECH2", lecturer: "Mr. Ajua Columbus", dept: "EEN", level: 400 },
  { code: "CIV234", name: "Introduction to Architecture", day: "THU", time: "09:00-11:00", hall: "FET-BFF-HALL1", lecturer: "Mackongo Jean Christian", dept: "CIV", level: 200 },
  { code: "MEF366", name: "Heat Transfer", day: "THU", time: "09:00-11:00", hall: "FET-TECH3", lecturer: "Dr. Temgoua / Prof. Fopah-Lele", dept: "MEF", level: 300 },
  { code: "CEF450", name: "Cloud Computing & SOA", day: "THU", time: "11:00-13:00", hall: "PG-LR5", lecturer: "Dr Djouela Inès", dept: "CEN", level: 400 },
  { code: "CEF352", name: "Tools & Numerical Methods", day: "THU", time: "11:00-13:00", hall: "FET-TECH2", lecturer: "Dr Wati / Dr Azeufack", dept: "CEN", level: 300 },
  { code: "EEF490", name: "Hybrid Energy Components & Systems", day: "THU", time: "11:00-13:00", hall: "FET-BFF-HALL1", lecturer: "Prof. Fopah / Dr. Wati", dept: "EEN", level: 400 },
  { code: "EEF268", name: "Digital Electronics II", day: "THU", time: "11:00-13:00", hall: "FET-BGFL", lecturer: "Wirnkar Basil / Ayuketah Yvan", dept: "EEN", level: 200 },
  { code: "CEF488", name: "System & Network Programming", day: "THU", time: "13:00-15:00", hall: "PG-LR5", lecturer: "Mr Forcha Glen", dept: "CEN", level: 400 },
  { code: "CEF482", name: "XML & Document Content Description", day: "THU", time: "13:00-15:00", hall: "FET-BFF-HALL1", lecturer: "Dr Sop", dept: "CEN", level: 400 },
  { code: "CEF354", name: "Switching & Routing Protocols", day: "THU", time: "15:00-17:00", hall: "PG-LR5", lecturer: "Dr Nkemeni V. / Dr Nguti", dept: "CEN", level: 300 },
  { code: "EEF360", name: "Systems Simulation & PCB Design", day: "THU", time: "15:00-17:00", hall: "FET-BGFL", lecturer: "Prof. Ngwashi / Dr. Tabetah", dept: "EEN", level: 300 },
  { code: "CEF444", name: "AI & Machine Learning", day: "FRI", time: "07:00-09:00", hall: "FET-BGFL", lecturer: "Prof. Fute / Dr. Sop", dept: "CEN", level: 400 },
  { code: "CEF342", name: "Database and Design", day: "FRI", time: "07:00-09:00", hall: "FET-TECH3", lecturer: "Eng. Kingue Patrick", dept: "CEN", level: 300 },
  { code: "EEF364", name: "Basic Telecommunications", day: "FRI", time: "07:00-09:00", hall: "FET-TECH4", lecturer: "Dr. Nkemeni / Mr. Forcha Glen", dept: "EEN", level: 300 },
  { code: "MEF204", name: "Basics of Mechanical Drawing", day: "FRI", time: "07:00-09:00", hall: "FET-BFF-HALL1", lecturer: "Dr. Temgoua / Dr. Aquigeh", dept: "MEF", level: 200 },
  { code: "CIV214", name: "Chemistry II", day: "FRI", time: "07:00-09:00", hall: "FET-TECH1", lecturer: "Tchetgnia Ngassam Ines", dept: "CIV", level: 200 },
  { code: "CIV310", name: "Thermodynamics", day: "FRI", time: "07:00-09:00", hall: "PG-LR5", lecturer: "Dr. Lontsi Agostiny", dept: "CIV", level: 300 },
  { code: "CPE208", name: "Chemical Process Principle", day: "FRI", time: "07:00-09:00", hall: "FET-TECH2", lecturer: "Dr Teiseh", dept: "CPE", level: 200 },
  { code: "CEF472", name: "Human Computer Interface", day: "FRI", time: "09:00-11:00", hall: "FET-TECH1", lecturer: "Dr Djouela Inès", dept: "CEN", level: 400 },
  { code: "CEF364", name: "Local Area Computer Network", day: "FRI", time: "09:00-11:00", hall: "FET-TECH2", lecturer: "Mr. Glen Forcha", dept: "CEN", level: 300 },
  { code: "EEF462", name: "Digital Signal Processing", day: "FRI", time: "09:00-11:00", hall: "FET-TECH3", lecturer: "Sitamtze Youmbi Bertrand", dept: "EEN", level: 400 },
  { code: "EEF480", name: "Control of Electrical Machines", day: "FRI", time: "09:00-11:00", hall: "FET-TECH4", lecturer: "Dr. Fotso", dept: "EEN", level: 400 },
  { code: "CIV402", name: "Reinforced Concrete I", day: "FRI", time: "09:00-11:00", hall: "FET-BGFL", lecturer: "Chia E", dept: "CIV", level: 400 },
  { code: "CIV344", name: "Solid Mechanics", day: "FRI", time: "09:00-11:00", hall: "PG-LR5", lecturer: "Dr. Feumoe Narcisse", dept: "CIV", level: 300 },
  { code: "CPE302", name: "Health Safety and Environment", day: "FRI", time: "09:00-11:00", hall: "FET-BFF-HALL1", lecturer: "Dr. Boukanda", dept: "CPE", level: 300 },
  { code: "CEF254", name: "Algebra", day: "FRI", time: "11:00-13:00", hall: "FET-BGFL", lecturer: "Dr Dor C.", dept: "CEN", level: 200 },
  { code: "CEF364", name: "Local Area Computer Network", day: "FRI", time: "11:00-13:00", hall: "FET-TECH1", lecturer: "Mr. Glen Forcha", dept: "CEN", level: 300 },
  { code: "CEF462", name: "Digital Image Processing", day: "FRI", time: "11:00-13:00", hall: "FET-BFF-HALL1", lecturer: "Dr Sop Deffo", dept: "CEN", level: 400 },
  { code: "EEF464", name: "Wireless & Mobile Communications", day: "FRI", time: "11:00-13:00", hall: "FET-BFF-HALL2", lecturer: "Dr. Sitamtze Youmbi", dept: "EEN", level: 400 },
  { code: "CIV202", name: "Materials Science & Technology", day: "FRI", time: "11:00-13:00", hall: "FET-TECH2", lecturer: "Tchetgnia Ngassam Ines", dept: "CIV", level: 200 },
  { code: "CPE304", name: "Reservoir Engineering", day: "FRI", time: "11:00-13:00", hall: "FET-TECH3", lecturer: "Dr. Victor Wotanie / Mr. Ayuk Samuel", dept: "CPE", level: 300 },
  { code: "CEF344", name: "Client-Server & Web App Development", day: "FRI", time: "13:00-15:00", hall: "PG-LR5", lecturer: "Dr Sop Deffo", dept: "CEN", level: 300 },
  { code: "CEF250", name: "Computer Architecture", day: "FRI", time: "13:00-15:00", hall: "FET-BGFL", lecturer: "Mr. Forcha Glen", dept: "CEN", level: 200 },
  { code: "EEF482", name: "Electric Machines II", day: "FRI", time: "13:00-15:00", hall: "FET-BFF-HALL2", lecturer: "Fotso Mbobda Christophe", dept: "EEN", level: 400 },
  { code: "CIV404", name: "Fluid Mechanics & Hydraulic Constructions", day: "FRI", time: "13:00-15:00", hall: "FET-TECH3", lecturer: "Lontsi Agostiny Marrios", dept: "CIV", level: 400 },
  { code: "MEF240", name: "Introduction to Thermodynamics", day: "FRI", time: "13:00-15:00", hall: "FET-TECH2", lecturer: "Prof. Fopah-Lele / Dr. Temgoua", dept: "MEF", level: 200 },
  { code: "CEF356", name: "Mobile Communications & Protocols", day: "FRI", time: "15:00-17:00", hall: "FET-BGFL", lecturer: "Dr Nkemeni V.", dept: "CEN", level: 300 },
  { code: "EEF466", name: "Antenna and Propagation", day: "FRI", time: "15:00-17:00", hall: "FET-TECH4", lecturer: "Engr. Baar David", dept: "EEN", level: 400 },
  { code: "EEF366", name: "Sequence Control", day: "FRI", time: "15:00-17:00", hall: "FET-TECH1", lecturer: "Dr. Nouadjep / Dr. Musong", dept: "EEN", level: 300 },
  { code: "MEF354", name: "Thermodynamics", day: "FRI", time: "15:00-17:00", hall: "FET-TECH2", lecturer: "Temgoua Djouatsa Diane", dept: "MEF", level: 300 },
  { code: "CIV422", name: "Structural Analysis II", day: "FRI", time: "15:00-17:00", hall: "PG-LR5", lecturer: "Njike M. & Kila S.", dept: "CIV", level: 400 },
  { code: "CIV210", name: "Fluid Mechanics", day: "FRI", time: "15:00-17:00", hall: "FET-BGFL", lecturer: "Dr. Lontsi / Dr. Mwebi", dept: "CIV", level: 200 },
  { code: "EEF484", name: "Electrical Power Systems II", day: "SAT", time: "07:00-09:00", hall: "FET-TECH1", lecturer: "Fotso Mbobda / Ayuketah", dept: "EEN", level: 400 },
  { code: "MEF202", name: "Materials Science and Technology", day: "SAT", time: "07:00-09:00", hall: "FET-BGFL", lecturer: "Dr. Awa", dept: "MEF", level: 200 },
  { code: "CIV410", name: "Fundamentals of BIM", day: "SAT", time: "07:00-09:00", hall: "FET-BFF-HALL1", lecturer: "Mr. Kang Cederic / Chia", dept: "CIV", level: 400 },
  { code: "EEF260", name: "Analog Electronics I", day: "SAT", time: "07:00-09:00", hall: "FET-TECH4", lecturer: "Dr. Tabeta Marshall", dept: "EEN", level: 200 },
  { code: "CEF346", name: "Object Oriented Programming", day: "SAT", time: "09:00-11:00", hall: "PG-LR5", lecturer: "Dr Djouela", dept: "CEN", level: 300 },
  { code: "CEF350", name: "Security and Cryptosystem", day: "SAT", time: "09:00-11:00", hall: "FET-TECH1", lecturer: "Dr Tsague A.", dept: "CEN", level: 300 },
  { code: "EEF474", name: "Coding Theory", day: "SAT", time: "09:00-11:00", hall: "FET-TECH2", lecturer: "Mr. Ajua Columbus", dept: "EEN", level: 400 },
  { code: "CIV222", name: "General Algebra & Affine Geometry", day: "SAT", time: "09:00-11:00", hall: "FET-BFF-HALL1", lecturer: "Agbor D. / Feumoe Narcisse", dept: "CIV", level: 200 },
  { code: "CIV334", name: "Strength of Materials", day: "SAT", time: "09:00-11:00", hall: "FET-TECH4", lecturer: "Njike Manette / Kila", dept: "CIV", level: 300 },
  { code: "MEF366", name: "Heat Transfer", day: "SAT", time: "09:00-11:00", hall: "FET-TECH3", lecturer: "Dr. Temgoua / Prof. Fopah-Lele", dept: "MEF", level: 300 },
  { code: "CEF450", name: "Cloud Computing & SOA", day: "SAT", time: "11:00-13:00", hall: "PG-LR5", lecturer: "Dr Djouela Inès", dept: "CEN", level: 400 },
  { code: "CEF352", name: "Tools & Numerical Methods", day: "SAT", time: "11:00-13:00", hall: "FET-TECH2", lecturer: "Dr Wati / Dr Azeufack", dept: "CEN", level: 300 },
  { code: "EEF490", name: "Hybrid Energy Components & Systems", day: "SAT", time: "11:00-13:00", hall: "FET-BFF-HALL1", lecturer: "Prof. Fopah / Dr. Wati", dept: "EEN", level: 400 },
  { code: "EEF268", name: "Digital Electronics II", day: "SAT", time: "11:00-13:00", hall: "FET-BGFL", lecturer: "Wirnkar Basil / Ayuketah Yvan", dept: "EEN", level: 200 },
  { code: "MEF460", name: "Design Graphics for Mech. Eng.", day: "SAT", time: "11:00-13:00", hall: "FET-TECH1", lecturer: "Dr. Aquigeh Newen", dept: "MEF", level: 400 },
  { code: "MEF268", name: "Electrical Eng. for Mech. Engineers", day: "SAT", time: "11:00-13:00", hall: "FET-TECH3", lecturer: "Simo Domguia Ulrich", dept: "MEF", level: 200 },
  { code: "CEF482", name: "XML & Document Content Description", day: "SAT", time: "13:00-15:00", hall: "FET-BFF-HALL1", lecturer: "Dr Sop", dept: "CEN", level: 400 },
  { code: "CEF488", name: "System & Network Programming", day: "SAT", time: "13:00-15:00", hall: "PG-LR5", lecturer: "Mr Forcha Glen", dept: "CEN", level: 400 },
  { code: "MEF368", name: "Design & Operation of Chemical Apparatus", day: "SAT", time: "13:00-15:00", hall: "FET-TECH1", lecturer: "Nouadjep Serge", dept: "MEF", level: 300 },
  { code: "MEF464", name: "Heating, Ventilation & Air Conditioning", day: "SAT", time: "13:00-15:00", hall: "FET-TECH3", lecturer: "Dr. Aquigeh Newen", dept: "MEF", level: 400 },
  { code: "CIV416", name: "Introduction to Urbanism & Transport", day: "SAT", time: "13:00-15:00", hall: "FET-BGFL", lecturer: "Tata Sunjo / Meh", dept: "CIV", level: 400 },
  { code: "CIV340", name: "Technical Writing", day: "SAT", time: "13:00-15:00", hall: "FET-TECH2", lecturer: "Prof. Tata S / Dr. Mwebi", dept: "CIV", level: 300 },
  { code: "EEF264", name: "Control Engineering Instrumentation", day: "SAT", time: "15:00-17:00", hall: "FET-TECH1", lecturer: "Dr. Nouadjep", dept: "EEN", level: 200 },
  { code: "CEF354", name: "Switching & Routing Protocols", day: "SAT", time: "15:00-17:00", hall: "FET-BGFL", lecturer: "Dr Nkemeni V. / Dr Nguti", dept: "CEN", level: 300 },
  { code: "CIV228", name: "Programming & Application Software", day: "SAT", time: "15:00-17:00", hall: "FET-TECH2", lecturer: "Dr. Nouadjep Serge", dept: "CIV", level: 200 },
  { code: "CIV342", name: "Architectural Drawing", day: "SAT", time: "15:00-17:00", hall: "FET-BFF-HALL1", lecturer: "Goodwill N", dept: "CIV", level: 300 },
  { code: "MEF370", name: "Process Technology & Design", day: "SAT", time: "15:00-17:00", hall: "PG-LR5", lecturer: "Dr. Tsamo Nestor", dept: "MEF", level: 300 },
  { code: "CEF474", name: "Software Verification & Validation", day: "SAT", time: "17:00-19:00", hall: "FET-BFF-HALL1", lecturer: "Dr Tsague A.", dept: "CEN", level: 400 },
  { code: "CEF458", name: "Enterprise IP, Telephony & Video Network", day: "SAT", time: "17:00-19:00", hall: "PG-LR5", lecturer: "Dr. Kamdjou", dept: "CEN", level: 400 },
  { code: "CIV418", name: "Quality, Safety & Environmental Mgmt", day: "SAT", time: "17:00-19:00", hall: "FET-BGFL", lecturer: "Ngassam Ines / Mwebi", dept: "CIV", level: 400 },
  { code: "MEF470", name: "Embedded Application Design & Interfacing", day: "SAT", time: "17:00-19:00", hall: "FET-TECH2", lecturer: "Ejuh Che", dept: "MEF", level: 400 },
];

export const DAYS = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'] as const;

export const DAY_FULL_NAMES: Record<string, string> = {
  MON: 'Monday',
  TUE: 'Tuesday',
  WED: 'Wednesday',
  THU: 'Thursday',
  FRI: 'Friday',
  SAT: 'Saturday',
};

export type DayOfWeek = typeof DAYS[number];
export type Department = 'CEN' | 'EEN' | 'CIV' | 'MEF' | 'CPE';
export type Level = 200 | 300 | 400 | 500;
